pipeline {
    agent none

    stages{
        stage("Build the runner container") {
            agent any

            steps {
                sh "docker build -t ramonagco/cloudbees-test:latest -f Dockerfile ."

                // I wanted to push the image and use it in the next step, but I would have
                // needed to configure credentials and well, I do not want to commit and
                // share credentials
                // sh "docker push ramonagco/cloudbees-test:latest"
            }
        }

        stage("Run the yamllint") {
            agent { dockerfile true }

            steps {
                sh "yamllint ."
            }
        }
    }
}
